### ISSUE TITLE
Downcompile with babel

### ISSUE THREAD

**Issue by justinmchase** [tsub/serverless-plugin-subscription-filter#2]
Turns out this plugin doesn't run on older versions of Node. I get an error when running on 4.3 (actual lambda on aws version):

> SyntaxError: Unexpected token =

I believe this is because the code in this plugin is only supported by newer versions of node unless you use babel. So it would be nice if you would down compile before publishing for use in older versions of node. I can try to hookup a PR tomorrow.

**Comment by tsub** [comment]
@justinmchase Sorry for late reply. We will support to Node.js 4.3 From now by #4.

**Comment by justinmchase** [comment]
Thanks! I did encouter this again at some point but my solution was to do the building in higher versions of node, this will be helpful thanks.
