### ISSUE TITLE
Is there a way to set the expiration time?

### ISSUE THREAD

**Issue by justinmchase** [tsub/serverless-plugin-subscription-filter#6]
It would be nice if default expiration time could be set here, so when the log group is created it would set it to that time.

**Comment by tsub** [comment]
Is that about the setting here? 👇 

https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/Working-with-log-groups-and-streams.html#SettingLogRetention

If so, I think that it is not the responsibility of this plugin.

**Comment by justinmchase** [comment]
Yeah, and that's fine.
